spring:
  datasource:
    url: jdbc:h2:file:./data/testdb   # 프로젝트 경로 밑에 data/testdb.mv.db 로 저장됨
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # create면 실행 때마다 테이블 다 날아감. update 권장
    show-sql: true
    properties:
      hibernate:
        format_sql: true
